spring:
  ai:
    #ollama:
      #chat:
        #model: deepcoder
    vectorstore:
      qdrant:
        collection-name: GameRules
    anthropic:
      chat:
        options:
          model: claude-3-7-sonnet-20250219
      api-key: ${KEY}

server:
  port: 8081

logging:
  level:
    org:
      zalando:
        logbook: TRACE


logbook:
  format:
    style: http